### ISSUE TITLE
The L20 graphics card is extremely slow

### ISSUE THREAD

**Issue by ChengRuiLiang** [jy0205/Pyramid-Flow#102]
The L20 graphics card is extremely slow 
![微信图片_20241015193709](https://github.com/user-attachments/assets/33f52b83-4530-4853-a2d7-bce4463078a7)
![微信图片_20241015193941](https://github.com/user-attachments/assets/fd8f0d61-45d3-448c-afbe-e81486385364)

**Comment by feifeiobama** [comment]
This generation speed is within our expected range, since the autoregressive models require frame-by-frame generation.

**Comment by ChengRuiLiang** [comment]
But no GPU memory is actually used

**Comment by feifeiobama** [comment]
> But no GPU memory is actually used

Could you run `watch -n 1 nvidia-smi` and check which stage does not use GPU memory: DiT generation or later VAE decoding?

**Comment by ChengRuiLiang** [comment]
It's always zero

**Comment by ChengRuiLiang** [comment]
![微信图片_20241017105306](https://github.com/user-attachments/assets/efc969b4-12b2-4962-ad9d-783f66c557a8)

**Comment by ChengRuiLiang** [comment]
video_generation_demo works fine
