### ISSUE TITLE
Fresh Installed but getting ERROR, No module named 'gradio'

### ISSUE THREAD

**Issue by chnisar515** [jy0205/Pyramid-Flow#103]
Hello Experts,
I have installed fresh copy of Pyramid-Flow in my Drive E: after install everything successfully and when i try this command (python app.py) to launch the program i am getting this error.

> (pyramid) E:\pyramidflow\Pyramid-Flow>python app.py
> Traceback (most recent call last):
>   File "app.py", line 3, in <module>
>     import gradio as gr
> ModuleNotFoundError: No module named 'gradio'

**Comment by feifeiobama** [comment]
Please install Gradio following [this link](https://www.gradio.app/guides/quickstart).

**Comment by chnisar515** [comment]
> Please install Gradio following [this link](https://www.gradio.app/guides/quickstart).

feifeiobama first of all thank you so much for quick reply. i am not a developer so can you guide me like a newbie? i mean did i only need to run this command

> pip install gradio

so whats the next step?

**Comment by chnisar515** [comment]
its working. i just use this command
`pip install gradio`
and after i run this command to launch program
`python app.py`
and now its downloading some models.
