### ISSUE TITLE
fp32 good quality

### ISSUE THREAD

**Issue by ptits** [jy0205/Pyramid-Flow#104]
I tried fp32 in it gave much better results in my test
Of course it took 2.5x more time and ate about 70GB of VRAM

But quality is better in t2v and i2v

Cant wait till new model will be released

https://github.com/user-attachments/assets/31bf44de-a30e-49bf-8658-feddf2b2a913

**Comment by ptits** [comment]
https://github.com/user-attachments/assets/e6b71d66-29d8-466f-a117-1845e98d6b42


a charming cartoon fox with bright eyes and a bushy tail. The fox sits in a forest setting, surrounded by trees and flowers. As it looks around curiously, it breaks into a warm, cheerful smile. Add a gentle head tilt and a slight wag of the tail to emphasize its playful nature.

**Comment by feifeiobama** [comment]
Thank you for sharing the new finding.
