### ISSUE TITLE
text encoder network details?

### ISSUE THREAD

**Issue by xuzukang** [jy0205/Pyramid-Flow#107]
I noticed that in your code, for the text encoder part, you used the clip and T5 models. Based on this, I have two questions: 1. Will the clip and T5 models update parameters during training? 2. What is the difference between these two clip models?
Looking forward to your answer, thank you

**Comment by feifeiobama** [comment]
We followed SD3 in the text encoder design, where these models are frozen during training. The two CLIP models are used separately for the text branch of MM-DiT and AdaLN.

**Comment by xuzukang** [comment]
In training process, only the parameters of MM-DiT and VAE will be updated?

**Comment by feifeiobama** [comment]
> In training process, only the parameters of MM-DiT and VAE will be updated?

The VAE is also frozen during training. We used pre-extracted VAE latents to train the MM-DiT.

**Comment by xuzukang** [comment]
> > In training process, only the parameters of MM-DiT and VAE will be updated?
> 
> The VAE is also frozen during training. We used pre-extracted VAE latents to train the MM-DiT.
Thank you very much for your answer, can I understand it as: The paper states that vae comes from MAGVIT, which means that vae encoder and vae decoder both come from the MAGVIT model and are not need training. only the MM-DiT needs trained?

**Comment by xuzukang** [comment]
> > > In training process, only the parameters of MM-DiT and VAE will be updated?
> > 
> > 
> > The VAE is also frozen during training. We used pre-extracted VAE latents to train the MM-DiT.
> > Thank you very much for your answer, can I understand it as: The paper states that vae comes from MAGVIT, which means that vae encoder and vae decoder both come from the MAGVIT model and are not need training. only the MM-DiT needs trained?

>Thank you for your great work. I really want to figure out the composition of each part of pyramid-flow: I now know that CLIP_1, CLIP_2, T5, MM-DiT come from SD3, of which only MM-DiT needs to be trained in pyramid-flow, VAE-encoder comes from MAGVIT and does not need to be trained. So where does VAE-decoder come from and does it need to be trained?

**Comment by feifeiobama** [comment]
The VAE encoder and decoder were trained from scratch, with some of the key design choices following MAGVIT-v2.

**Comment by xuzukang** [comment]
>> The VAE encoder and decoder were trained from scratch, with some of the key design choices following MAGVIT-v2.

>Got it, thank you very much for your answer
