### ISSUE TITLE
 Error no file named diffusion_pytorch_model.safetensors found in directory 

### ISSUE THREAD

**Issue by mehulgupta2016154** [jy0205/Pyramid-Flow#11]
Getting this error while following the demo codes: Actually the safetensors file isn't present when downloading the model checkpoints (verified in the folder)

Please install flash attention
An error occurred while trying to fetch /content/diffusion_transformer_384p: Error no file named diffusion_pytorch_model.safetensors found in directory /content/diffusion_transformer_384p.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
using half precision
Using temporal causal attention
We interp the position embedding of condition latents

**Comment by jy0205** [comment]
Thanks for your attention! You can ignore this ERROR message from huggingface transformers (Since we do not use safetensors). It does not effect the usage,
