### ISSUE TITLE
Add portrait mode

### ISSUE THREAD

**Issue by RodTDai** [jy0205/Pyramid-Flow#110]
Hey guys, please add portrait mode (when detected the image to image-video is in portrait ratio.
i tried to swap resolution on app.py, it "works" but the video get scrambled after 2-3 frames!

Thanks.

**Comment by feifeiobama** [comment]
Thank you for your valuable feedback. Our model does not support portrait mode because most open-source video training data is widescreen.

**Comment by RodTDai** [comment]
ah, that is understandable... 
neverheless, i'm wondering, if we generate in landscape mode and adjust the crop for match the protrait in a second step?
i mean, this is probably what commercial ones do, right? because in my tests, the landscape and protrait generations does not differ, so i think it is acting in same training data (landscape) even when producing protrait outputs that matches image. Thanks for the good work!
The main think i believe need to be addressed is consistency, right now the elements on image morpth too much or too fast.

**Comment by feifeiobama** [comment]
Thank you for the valuable advice. I think the portrait mode can be supported by finetuning the model with the corresponding videos. We are working on the consistency issue and will share a new video generation checkpoint soon.
