### ISSUE TITLE
Rough estimate when training code will release

### ISSUE THREAD

**Issue by jcho19** [jy0205/Pyramid-Flow#111]
Hi,
I was wondering if you could give a rough estimate when the training code will be released? also will we be able to adjust the resolution and number of frames  for training? Thank you!

**Comment by jy0205** [comment]
We are still working on the new model checkpoint and will share the training code after that.  About one week. Thanks for your attention again.

**Comment by feifeiobama** [comment]
We have open-sourced the training code, please feel free to use them and report any issues.
