### ISSUE TITLE
Unfortuantely I got this !!!

### ISSUE THREAD

**Issue by techshoww** [jy0205/Pyramid-Flow#114]
![image](https://github.com/user-attachments/assets/2c22e607-d754-4698-8bef-45ba2ef02e02)

**Comment by feifeiobama** [comment]
We are working on a new model checkpoint trained from scratch (instead of using the SD3 weight initialization). It has shown much improvement in human faces and bodies. Please stay tuned.

**Comment by feifeiobama** [comment]
We have uploaded new model checkpoints based on the FLUX structure and much improved human structure. Please check them out :D
