### ISSUE TITLE
About training detail

### ISSUE THREAD

**Issue by WangFeng18** [jy0205/Pyramid-Flow#119]
Hi, thanks for sharing the great project.

I have found the mmdit in your method can accept different stages as input, and different stage are concatenated in token dimension. This may require the timestep to be same in different stages but different stages have their respective timestep interval. I wonder if the training sampled for each batch only include one stage, or my understanding is wrong in something. Looking forward for your reply, and thanks again for the excellent project!

**Comment by feifeiobama** [comment]
> Hi, thanks for sharing the great project.
> 
> I have found the mmdit in your method can accept different stages as input, and different stage are concatenated in token dimension. This may require the timestep to be same in different stages but different stages have their respective timestep interval. I wonder if the training sampled for each batch only include one stage, or my understanding is wrong in something. Looking forward for your reply, and thanks again for the excellent project!

In the original implementation, we composed the training batch so that it contained different stages uniformly. In the newest version (expected to release soon), we have optimized the procedure so that it contains three stages by 25%/50%/25% which shows certain improvement.

**Comment by WangFeng18** [comment]
Thanks

**Comment by MoayedHajiAli** [comment]
Hello @feifeiobama 
In the original training setup where one batch contains one stage only, how did you handle the batchsize? Did you use 16x the batchsize for the first stage compared with the last stage? (to keep an equal number of token per batch)? 

Thank you!
