### ISSUE TITLE
how much minimum vram needed to run the 768p and 384p model locally

### ISSUE THREAD

**Issue by SAT431** [jy0205/Pyramid-Flow#12]

**Comment by jy0205** [comment]
The 384p version requires around 26GB memory, and the 768p version requires around 40GB memory (we do not have the exact number because the cache mechanism on 80GB GPU)

**Comment by SAT431** [comment]
will it get optimized to like upto 12 or 16gb vram in future

**Comment by bghira** [comment]
buying new GPU probably easier than to bring VRAM use down lol

**Comment by afnanqasim74** [comment]
> buying new GPU probably easier than to bring VRAM use down lol

i thank @SAT431  is asking about any quantization would be possible in future so it could be loaded on colab easily ?

**Comment by FurkanGozukara** [comment]
We need quantization and optimizations 

Flux fine tuning is down to as low as 6 gb atm.
Yes entire model training not inference 12b params

**Comment by feifeiobama** [comment]
Thanks to [@Ednaordinary](https://github.com/Ednaordinary)'s contribution, our model now supports CPU offloading to allow inference with less than 12GB of GPU memory by adding a `cpu_offloading=True` parameter. See https://github.com/jy0205/Pyramid-Flow/pull/23 for details.

**Comment by sumitmamoria** [comment]
Can this work on a dual 3090?

**Comment by SAT431** [comment]
> Can this work on a dual 3090?

Yes, when cpu_offloading=True is enabled.

**Comment by sumitmamoria** [comment]
> > Can this work on a dual 3090?
> 
> Yes, when cpu_offloading=True is enabled.

That would push the model to CPU, no? I am trying to do the opposite, by pushing the model over two GPUs to avoid CPU offloading.

**Comment by feifeiobama** [comment]
> > > Can this work on a dual 3090?
> > 
> > 
> > Yes, when cpu_offloading=True is enabled.
> 
> That would push the model to CPU, no? I am trying to do the opposite, by pushing the model over two GPUs to avoid CPU offloading.

@jy0205 is working on multi-gpu inference. We hope to share the progress within a few days.

**Comment by MidnightFiend** [comment]
on a single V100-SXM2-32GB, with cpu_offloading=True , 384p still OOM
