### ISSUE TITLE
Full 3D attention

### ISSUE THREAD

**Issue by agneet42** [jy0205/Pyramid-Flow#120]
Hi, thanks for the great work!

As mentioned in the paper, you employ full 3D attention instead of factorized spatial and temporal attention. I was wondering if this is the LOC that refers to the same : https://github.com/jy0205/Pyramid-Flow/blob/main/pyramid_dit/modeling_mmdit_block.py#L396 ; if not would you be able to point me to the same?
<img width="543" alt="image" src="https://github.com/user-attachments/assets/052d6b6f-1b35-44ac-96c2-b1b5cb7ea9ce">

**Comment by jy0205** [comment]
Yes, this class is full-sequence attention.

**Comment by agneet42** [comment]
Thanks!
