### ISSUE TITLE
Do you check the number of frames for the video?

### ISSUE THREAD

**Issue by AA-Developer** [jy0205/Pyramid-Flow#123]
hi
Just a tip, pay attention to it.
In my experience with video models when using internet video dataset, the number of frames is usually different in each video even if the source says so, so it is better to make a filter that checks the number of video frames because the unstable distortion is caused by the different number of frames for each video.

**Comment by feifeiobama** [comment]
Thank you for sharing this tip, we have carefully handled the different number of frames for each video. Stay tuned for a better model coming soon!
