### ISSUE TITLE
OOM on 2x4090?

### ISSUE THREAD

**Issue by gameveloster** [jy0205/Pyramid-Flow#126]
Getting OOM when using 2x4090.

Trying `t2v` using `save_memory=True`, `cpu_offloading=False`, `variant=diffusion_transformer_768p`, `inference_multigpu=True`, `bf16`.

Is the model expected to fit into 2x4090, total 48 GB VRAM?

**Comment by feifeiobama** [comment]
Did you test with `scripts/inference_multigpu.sh` or `scripts/app_multigpu_engine.sh`? I think the model should fit into 2x4090 according to https://github.com/jy0205/Pyramid-Flow/pull/59#issue-2583549693.
