### ISSUE TITLE
Very slow to loading checkpoint shards and convert tokenizer - Tesla P40

### ISSUE THREAD

**Issue by gandolfi974** [jy0205/Pyramid-Flow#127]
hello,

Using a Tesla P40 on windows. the app is very slow to loading checkpoint and convert tokenizer

`You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|█████████████████████████████████████████| 2/2 [04:22<00:00, 131.28s/it]`

- Is it normal ?

i have tried this tips but nothing change https://discuss.huggingface.co/t/error-with-new-tokenizers-urgent/2847/4

```
    Uninstalled transformers
    Installed transformers sentencepiece like this : !pip install --no-cache-dir transformers sentencepiece
    Use_fast= False like this: tokenizer = AutoTokenizer.from_pretrained(“XXXXX”, use_fast=False)
```

thanks

**Comment by feifeiobama** [comment]
The output is normal, see https://github.com/jy0205/Pyramid-Flow/issues/34#issuecomment-2408554153.

However, the slow checkpoint loading is unusual, could you check your RAM usage?

**Comment by gandolfi974** [comment]
![2024-10-20 18_15_02-Very slow to loading checkpoint shards and convert tokenizer - Tesla P40 · Issue](https://github.com/user-attachments/assets/56b26701-8119-4f35-9024-89e922976954)

**Comment by feifeiobama** [comment]
> ![2024-10-20 18_15_02-Very slow to loading checkpoint shards and convert tokenizer - Tesla P40 · Issue](https://private-user-images.githubusercontent.com/25908976/378204963-56b26701-8119-4f35-9024-89e922976954.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDE0MDMsIm5iZiI6MTcyOTQ0MTEwMywicGF0aCI6Ii8yNTkwODk3Ni8zNzgyMDQ5NjMtNTZiMjY3MDEtODExOS00ZjM1LTkwMjQtODllOTIyOTc2OTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE2MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYWFiZDVmNDU2OGRlMmI2NjlmYWJlNzMzZTNjODI5MmY1YzAwZjU3NzhmYWI5ZDJiNDE4ZDdiODNlM2M3YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rJiUGPJIg2zXQ5Tk0KwLXJSlkWWfLkMADQep1fPpMU0)

According to this, the bottleneck seems to be reading from HDD.
