### ISSUE TITLE
Please add a gradio demo with all possible optimizations the community need it

### ISSUE THREAD

**Issue by FurkanGozukara** [jy0205/Pyramid-Flow#13]
Like FP8 or FP4 loading, CPU offloading, and such

Also all features of the paper

thank you so much

**Comment by feifeiobama** [comment]
We are currently working on the gradio demo. Stay tuned.

**Comment by tin2tin** [comment]
@feifeiobama 
What about included in Diffusers?

**Comment by feifeiobama** [comment]
The gradio demo is contributed by [@tpc2233](https://github.com/tpc2233). We currently have no plans to integrate it into Diffusers. Closing the issue.
