### ISSUE TITLE
What is the total number of training images?

### ISSUE THREAD

**Issue by gobigrassland** [jy0205/Pyramid-Flow#134]
Based on the description in the paper, along with the issue #80 mentioning the use of [LAION-Aesthetics 6.5+](https://huggingface.co/datasets/bhargavsdesai/laion_improved_aesthetics_6.5plus_with_images), the total number of images is around 36M(11M + 6.9M + 4.4M + 14M + 169k). Is that correct?

**Comment by feifeiobama** [comment]
> Based on the description in the paper, along with the issue #80 mentioning the use of [LAION-Aesthetics 6.5+](https://huggingface.co/datasets/bhargavsdesai/laion_improved_aesthetics_6.5plus_with_images), the total number of images is around 36M(11M + 6.9M + 4.4M + 14M + 169k). Is that correct?

I checked again and here is the detailed situation:
* In the early training of the currently released model, we also used LAION-Aesthetics 5+, which contains more than 100M images.
* During the training of the new model (to be released soon), we find that removing all LAION datasets is beneficial for the generation quality. So it is recommended to train the model on the remaining datasets, which are around 10M images.

**Comment by gobigrassland** [comment]
OK, Thanks. Very Detailed !
