### ISSUE TITLE
MultiGPU fp16 Availability

### ISSUE THREAD

**Issue by philbanjo55** [jy0205/Pyramid-Flow#138]
Hello,
I know yall said the model isnt compatible with fp16, but then why 
In the file "app_multi_gpu_engine.py" line 61, does it give it as an option?  Is this a feature you plan on implementing?

    if model_dtype == "bf16":
        torch_dtype = torch.bfloat16 
    elif model_dtype == "fp16":
        torch_dtype = torch.float16
    else:
        torch_dtype = torch.float32

**Comment by feifeiobama** [comment]
> 意味着 NVIDA RTX系列无法使用？

RTX series should be able to run the code with bf16 :)
