### ISSUE TITLE
Setup instructions 

### ISSUE THREAD

**Issue by AshD** [jy0205/Pyramid-Flow#14]
I create a new conda env on a Ubuntu 24 linux 
conda create --name pyramid python=3.10

Did a git clone of this project and then ran pip install -r requirements.txt
And it throws errors that it can't find a compatible scipy package and tries to build one and fail. 

Do you have alternate setup instructions?

Thanks,
Ash

**Comment by feifeiobama** [comment]
Thank you for your interest in our project. We are using a Python version of 3.8.10, perhaps re-running the commands with `conda create --name ENV_NAME python==3.8.10` will solve the problem.

**Comment by FurkanGozukara** [comment]
@feifeiobama please upgrade to python 3.10

python 3.8 is history

**Comment by AshD** [comment]
Thanks python 3.8.10 worked! closing...
