### ISSUE TITLE
What is the 1024p image checkpoint? Is it a text-to-image model, or is it an image-to-video model?

### ISSUE THREAD

**Issue by SAT431** [jy0205/Pyramid-Flow#141]

**Comment by feifeiobama** [comment]
It is a text-to-image model.

**Comment by hashnimo** [comment]
You can still generate higher-resolution videos using the 384p image-to-video model. For example, if you input a 1024x576 resolution image, the output video will maintain that same resolution.

**Comment by feifeiobama** [comment]
> You can still generate higher-resolution videos using the 384p image-to-video model. For example, if you input a 1024x576 resolution image, the output video will maintain that same resolution.
> 
> To enable this, you can modify the following code [here](https://github.com/jy0205/Pyramid-Flow/blob/main/video_generation_demo.ipynb): `image.resize((width, height))`

Great observation, that would be relying entirely on RoPE's extrapolation capabilities. We also found it on images, but haven't tested it for video generation.
