### ISSUE TITLE
Error during text-to-video generation: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by axiomgraph** [jy0205/Pyramid-Flow#143]
It would be helpful if you mention what cuda package should I install. and also what version of visual studio builds tools should be installed(I mean I done it but it will be useful for other users)

**Comment by feifeiobama** [comment]
Sure, I think the following two installation guides might be useful:
* [CUDA](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html), which also specifies the visual studio version.
* [PyTorch](https://pytorch.org/get-started/previous-versions/)

**Comment by axiomgraph** [comment]
Thanks Tried 12.1
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
may be you should include it in read me section
