### ISSUE TITLE
what is difference between pyramid_flow_miniflux_bf16_v1.safetensors and pyramid_flow_miniflux_bf16_v2.safetensors ?

### ISSUE THREAD

**Issue by ptits** [jy0205/Pyramid-Flow#145]
any chance to have fp32 version or it does not make sense?

**Comment by jy0205** [comment]
Sorry, what do you mean by pyramid_flow_miniflux_bf16_v1 or pyramid_flow_miniflux_bf16_v2? We do not provide such checkpoints.

**Comment by aigcchumen** [comment]
> 抱歉，金字塔_流_迷你流_bf16_v1 或金字塔_流_迷你流_bf16_v2 是什么意思？我们不提供此类检查点。

这是kijai的版本 https://github.com/kijai/ComfyUI-PyramidFlowWrapper

**Comment by aigcchumen** [comment]
> 是否有机会拥有 FP32 版本，否则没有意义？

This is kijai's version https://github.com/kijai/ComfyUI-PyramidFlowWrapper

It is suggested that you should ask kijai.

**Comment by ptits** [comment]
![Uploading shot_241031_194212.png…]()
