### ISSUE TITLE
Questions about implementation

### ISSUE THREAD

**Issue by yjhong89** [jy0205/Pyramid-Flow#148]
Hi! Thanks for sharing training code!

While I analyzing implementation in details and have few questions.

1. https://github.com/jy0205/Pyramid-Flow/blob/e4b02ef31edba13e509896388b1fedd502ea767c/pyramid_dit/pyramid_dit_for_video_gen_pipeline.py#L451
  - Why use indexing `[index::column_size]` ? Since `latent_list[i_s]` would have shape of `[bs, c, t, h, w]` so 
  `latents_list[i_s][index::column_size]` means just getting one batch, isn't it?
  
2. How video sync group works?
  - If I use 8 gpus and default parallel group hyper-parameter setting, sp_group_size and video_sync_group would be 8.
  - Since sequential parallel already split long tokens so every gpu gets access to the same video input, why video_sync_group is necessary??

3. When extract video latent in advance, all videos have same fps ?? Since this line means if "frame" is not specified in annotation, extract first 121 frames
  - https://github.com/jy0205/Pyramid-Flow/blob/e4b02ef31edba13e509896388b1fedd502ea767c/tools/extract_video_vae_latents.py#L118

4. Why multiplying 2 in here? to preserve variance for each stage ?
  - https://github.com/jy0205/Pyramid-Flow/blob/e4b02ef31edba13e509896388b1fedd502ea767c/pyramid_dit/pyramid_dit_for_video_gen_pipeline.py#L424

Thanks!

**Comment by jy0205** [comment]
Here are the answers to your questions:
1. `latents_list[i_s][index::column_size]` aims to get a batch of samples that belong to the same stage.
2. We do not use the sequence parallel in the training. The code about sequence parallel is for the multi-gpu inference. The param `video_sync_group` is for controlling the group of processes that accept the same input sample.
3. We directly use 24 fps for training. The `frames` key means you can specify the frame indexes you want to extract.
4. Multiplying is to make the variance of noise still equal to 1 after bilinear interpolation. (Statisfy standard Gaussian)

**Comment by yjhong89** [comment]
Thanks!

**Comment by yjhong89** [comment]
Another questions

- Supports I2V training ? Current implementations seems only support t2v.

**Comment by yjhong89** [comment]
Yes, sounds right. autoregressive training naturally doing I2V training.
- Looking forward to share! Thanks.

Another question ?
- Then, why scale factor for first frame and remaining frames is different ?? (using same vae)
- https://github.com/jy0205/Pyramid-Flow/blob/e4b02ef31edba13e509896388b1fedd502ea767c/pyramid_dit/pyramid_dit_for_video_gen_pipeline.py#L582

**Comment by feifeiobama** [comment]
Great observation! Please refer to https://github.com/jy0205/Pyramid-Flow/issues/28#issuecomment-2406892327.

**Comment by yjhong89** [comment]
Thanks for quick answer!
