### ISSUE TITLE
Can this model produce infinitely long videos?

### ISSUE THREAD

**Issue by xizaoqu** [jy0205/Pyramid-Flow#155]
Hi, thanks for presenting this incredible work. Since the architecture is auto-regressive, can it be extended to generate infinitely long videos?

**Comment by feifeiobama** [comment]
Technically yes, but we have not resolved the quality degradation in autoregressive generation. Please refer to Diffusion Forcing (https://arxiv.org/abs/2407.01392) and GameNGen (https://arxiv.org/abs/2408.14837) for their design details.

**Comment by xizaoqu** [comment]
Thanks for your reply.
