### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by unbreakablepunjab** [jy0205/Pyramid-Flow#16]
so i cloned the the repo then installed requirments and then downloaded model in dir , it throw error when i run ur code "from pyramid_dit import PyramidDiTForVideoGeneration" cannot be imported

**Comment by feifeiobama** [comment]
Please run the inference code in the repo root directory, or follow https://github.com/jy0205/Pyramid-Flow/issues/6#issuecomment-2404551238 to add it to your system path.
