### ISSUE TITLE
Enhancing the straightness of the flow trajectory.

### ISSUE THREAD

**Issue by levon-khachatryan** [jy0205/Pyramid-Flow#161]
Hi! 

First of all, congrats on your great work, and thank you for open-sourcing it!
Can you explain in more detail why equations 9 and 10 from the paper should enhance the straightness of the flow trajectory?

Thanks in advance.

**Comment by feifeiobama** [comment]
The straightness of the flow trajectory is usually compromised when there are intersections. By using independent noise for the endpoints, it creates random directions in latent space for each trajectory, increasing the probability that different trajectories will intersect. Instead, by coupling the sampling of these endpoints, we can create more organized, possibly parallel trajectories with fewer intersections, thus improving straightness.

**Comment by levon-khachatryan** [comment]
Thanks for the answer.
