### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nikolay-ulyanov** [jy0205/Pyramid-Flow#17]
Could you clarify the license, please? Are the weights also available under MIT license? If so, could you explain, please, how do you base your model on SD3, if SD3 had a custom license, which is probably not commercial friendly (but I'm not a lawyer, so sorry if the wording is wrong here), while MIT allows commercial use?

**Comment by feifeiobama** [comment]
Sorry, we are not specialists in these licenses. We will modify the license of the SD initialized weight if there are such requests. In the meantime, we commit to releasing the next model checkpoint trained from scratch under the MIT license.

**Comment by nikolay-ulyanov** [comment]
Thanks for reply! Yeah, I also think MIT license would be awesome, but let's see.
(Just to reiterate, I'm also not a specialist (and not a representative of stability ai anyway))

**Comment by jy0205** [comment]
Thanks for your kind reminder! We have updated the model weight license based on SD3.
