### ISSUE TITLE
Can you fix the demo huggingface please?

### ISSUE THREAD

**Issue by ghost** [jy0205/Pyramid-Flow#18]
the question is solved thanks for replying! not sure how to delete the issue im sorry

**Comment by feifeiobama** [comment]
This is due to the GPU quota limit, so it can only generate 25 frames at a time. We have two options to play it at 1 second & 24 fps or 3 seconds & 8 fps.

We could not decide which is better, both are very unfortunate compromises. Now we have added an FPS control button so you can choose.

**Comment by feifeiobama** [comment]
Thank you for your suggestion, we will continue to improve the model and look into these hosting platforms.
