### ISSUE TITLE
Train DIT error: not support loading text feature directly

### ISSUE THREAD

**Issue by LaLaLailalai** [jy0205/Pyramid-Flow#181]
Hi @jy0205, 
Thanks for the great work!
I tried to run train_pyramid_flow_without_ar.sh, found OOM problem. 
So I try to remove the "load_text_encoder" and another error occurred, which is self.null_text_embeds wasn't defined, please check [here](https://github.com/jy0205/Pyramid-Flow/blob/3fc05bcd43a2e2523fcb48289d0acf7b21a1f134/pyramid_dit/pyramid_dit_for_video_gen_pipeline.py#L610).
Do you know how to solve it?

**Comment by jy0205** [comment]
Hi! You should pre-compute the null text embeds, (encode null str ""), you can refer to this issue https://github.com/jy0205/Pyramid-Flow/issues/160
