### ISSUE TITLE
Cannot generate a video - Crash : OSError: Unable to load weights from checkpoint file

### ISSUE THREAD

**Issue by visualbruno** [jy0205/Pyramid-Flow#19]
When I first run the python code, it says it does not find the file "diffusion_pytorch_model.safetensors":

> using half precision
> An error occurred while trying to fetch checkpoints\diffusion_transformer_768p: Error no file named 
> diffusion_pytorch_model.safetensors found in directory checkpoints\diffusion_transformer_768p.
> Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
> Using temporal causal attention
> We interp the position embedding of condition latents
> You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
> Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
> The latent dimmension channes is 16
> Traceback (most recent call last):
>   File "C:\Python312\Lib\site-packages\diffusers\models\model_loading_utils.py", line 105, in load_state_dict
>     return safetensors.torch.load_file(checkpoint_file, device="cpu")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\safetensors\torch.py", line 313, in load_file
>     with safe_open(filename, framework="pt", device=device) as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python312\Lib\site-packages\diffusers\models\model_loading_utils.py", line 116, in load_state_dict
>     if f.read().startswith("version"):
>        ^^^^^^^^
>   File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1887: character maps to <undefined>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Git\Pyramid-Flow\Video.py", line 32, in <module>
>     model = PyramidDiTForVideoGeneration(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Git\Pyramid-Flow\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 105, in __init__
>     self.vae = CausalVideoVAE.from_pretrained(os.path.join(model_path, 'causal_video_vae'), torch_dtype=torch_dtype, interpolate=False)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\diffusers\models\modeling_utils.py", line 735, in from_pretrained
>     state_dict = load_state_dict(model_file, variant=variant)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\diffusers\models\model_loading_utils.py", line 128, in load_state_dict
>     raise OSError(
> OSError: Unable to load weights from checkpoint file for 'checkpoints\causal_video_vae\diffusion_pytorch_model.safetensors' at 'checkpoints\causal_video_vae\diffusion_pytorch_model.safetensors'.
> 

---

So I renamed the file "diffusion_pytorch_model.bin" into "diffusion_pytorch_model.safetensors", but it still crashes:

> using half precision
> Using temporal causal attention
> We interp the position embedding of condition latents
> Traceback (most recent call last):
>   File "C:\Python312\Lib\site-packages\diffusers\models\model_loading_utils.py", line 105, in load_state_dict
>     return safetensors.torch.load_file(checkpoint_file, device="cpu")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\safetensors\torch.py", line 313, in load_file
>     with safe_open(filename, framework="pt", device=device) as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python312\Lib\site-packages\diffusers\models\model_loading_utils.py", line 116, in load_state_dict
>     if f.read().startswith("version"):
>        ^^^^^^^^
>   File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 233: character maps to <undefined>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Git\Pyramid-Flow\Video.py", line 32, in <module>
>     model = PyramidDiTForVideoGeneration(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Git\Pyramid-Flow\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 89, in __init__
>     self.dit = PyramidDiffusionMMDiT.from_pretrained(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\diffusers\models\modeling_utils.py", line 735, in from_pretrained
>     state_dict = load_state_dict(model_file, variant=variant)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\diffusers\models\model_loading_utils.py", line 128, in load_state_dict
>     raise OSError(
> OSError: Unable to load weights from checkpoint file for 'checkpoints\diffusion_transformer_768p\diffusion_pytorch_model.safetensors' at 'checkpoints\diffusion_transformer_768p\diffusion_pytorch_model.safetensors'.

**Comment by feifeiobama** [comment]
This is probably due to a wrong relative path and has nothing to do with safetensors (see https://github.com/jy0205/Pyramid-Flow/issues/11). Can you try to rename the file back to its original name and use the absolute path?

**Comment by visualbruno** [comment]
I did it. Apparently, the problem comes from the file causal_video_vae\diffusion_pytorch_model.safetensors

> using half precision
> An error occurred while trying to fetch checkpoints\diffusion_transformer_768p: Error no file named diffusion_pytorch_model.safetensors found in directory checkpoints\diffusion_transformer_768p.
> Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
> Using temporal causal attention
> We interp the position embedding of condition latents
> You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
> Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.71s/it]
> The latent dimmension channes is 16
> Traceback (most recent call last):
>   File "C:\Python312\Lib\site-packages\diffusers\models\model_loading_utils.py", line 105, in load_state_dict
>     return safetensors.torch.load_file(checkpoint_file, device="cpu")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\safetensors\torch.py", line 313, in load_file
>     with safe_open(filename, framework="pt", device=device) as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python312\Lib\site-packages\diffusers\models\model_loading_utils.py", line 116, in load_state_dict
>     if f.read().startswith("version"):
>        ^^^^^^^^
>   File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1887: character maps to <undefined>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Git\Pyramid-Flow\Video.py", line 9, in <module>
>     model = PyramidDiTForVideoGeneration(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Git\Pyramid-Flow\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 105, in __init__
>     self.vae = CausalVideoVAE.from_pretrained(os.path.join(model_path, 'causal_video_vae'), torch_dtype=torch_dtype, interpolate=False)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\diffusers\models\modeling_utils.py", line 735, in from_pretrained
>     state_dict = load_state_dict(model_file, variant=variant)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\diffusers\models\model_loading_utils.py", line 128, in load_state_dict
>     raise OSError(
> OSError: Unable to load weights from checkpoint file for 'checkpoints\causal_video_vae\diffusion_pytorch_model.safetensors' at 'checkpoints\causal_video_vae\diffusion_pytorch_model.safetensors'.

---

Python file I used:

> import torch
> from PIL import Image
> from pyramid_dit import PyramidDiTForVideoGeneration
> from diffusers.utils import load_image, export_to_video
> 
> torch.cuda.set_device(0)
> model_dtype, torch_dtype = 'bf16', torch.bfloat16   # Use bf16, fp16 or fp32	
> 
> model = PyramidDiTForVideoGeneration(
>     'checkpoints',                                         # The downloaded checkpoint dir
>     model_dtype,
>     model_variant='diffusion_transformer_768p',     # 'diffusion_transformer_384p'
> )
> 
> model.vae.to("cuda")
> model.dit.to("cuda")
> model.text_encoder.to("cuda")
> model.vae.enable_tiling()
> 
> prompt = "A movie trailer featuring the adventures of the 30 year old space man wearing a red wool knitted motorcycle helmet, blue sky, salt desert, cinematic style, shot on 35mm film, vivid colors"
> 
> with torch.no_grad(), torch.cuda.amp.autocast(enabled=True, dtype=torch_dtype):
>     frames = model.generate(
>         prompt=prompt,
>         num_inference_steps=[20, 20, 20],
>         video_num_inference_steps=[10, 10, 10],
>         height=768,     
>         width=1280,
>         temp=16,                    # temp=16: 5s, temp=31: 10s
>         guidance_scale=9.0,         # The guidance for the first frame, set it to 7 for 384p variant
>         video_guidance_scale=5.0,   # The guidance for the other video latent
>         output_type="pil",
>         save_memory=True,           # If you have enough GPU memory, set it to `False` to improve vae decoding speed
>     )
> 
> export_to_video(frames, "./text_to_video_sample.mp4", fps=24)

**Comment by feifeiobama** [comment]
We have just updated the Hugging Face models to safetensors format. Could you try downloading them and see if there are any remaining issues?

**Comment by visualbruno** [comment]
Hi.

I re-downloaded everything and I don't see anymore the bug about the safetensors files, but it still crashes:

> using half precision
> Using temporal causal attention
> We interp the position embedding of condition latents
> You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
> Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.58s/it]
> The latent dimmension channes is 16
> Traceback (most recent call last):
>   File "C:\Git\Pyramid-Flow\Video.py", line 9, in <module>
>     model = PyramidDiTForVideoGeneration(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Git\Pyramid-Flow\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 129, in __init__
>     self.scheduler = PyramidFlowMatchEulerDiscreteScheduler(
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\diffusers\configuration_utils.py", line 653, in inner_init
>     init(self, *args, **init_kwargs)
>   File "C:\Git\Pyramid-Flow\diffusion_schedulers\scheduling_flow_matching.py", line 66, in __init__
>     self.init_sigmas_for_each_stage()
>   File "C:\Git\Pyramid-Flow\diffusion_schedulers\scheduling_flow_matching.py", line 146, in init_sigmas_for_each_stage
>     self.timesteps_per_stage[i_s] = torch.from_numpy(timesteps[:-1])
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: expected np.ndarray (got Tensor)

I found on the web that's a problem of numpy. I installed the version 1.26.0, and it worked.

Thank you

**Comment by FurkanGozukara** [comment]
@feifeiobama can you update gradio demo for safetensors  that is what people loves

**Comment by feifeiobama** [comment]
> @feifeiobama can you update gradio demo for safetensors that is what people loves

Could you be more specific? I think the current Gradio demo is compatible with safetensors downloaded from Huggingface.

**Comment by FurkanGozukara** [comment]
@feifeiobama my bad i though single safetensors file were added instead of repo clone thank you

**Comment by KleinXin** [comment]
> > [@feifeiobama](https://github.com/feifeiobama) can you update gradio demo for safetensors that is what people loves
> 
> Could you be more specific? I think the current Gradio demo is compatible with safetensors downloaded from Huggingface.

Where is the safetensors file？I can only see bin file in rain1011/pyramid-flow-miniflux/causal_video_vae folder.
