### ISSUE TITLE
训练loss值为负数

### ISSUE THREAD

**Issue by catsled** [jy0205/Pyramid-Flow#204]
![image](https://github.com/user-attachments/assets/0f6b3046-c50d-4b8c-943f-c29b4f31ebba)

这是正常的吗，训练vae

**Comment by jy0205** [comment]
请问你是否是加入了discriminator的loss，我们现在的vae没有加入discriminator的对抗损失；如果加入对抗损失有可能出现这一项为负数

**Comment by catsled** [comment]
> 请问你是否是加入了discriminator的loss，我们现在的vae没有加入discriminator的对抗损失；如果加入对抗损失有可能出现这一项为负数

是的，我确实加入了，感谢回复
