### ISSUE TITLE
"I'm unable to make any progress."

### ISSUE THREAD

**Issue by bihmet** [jy0205/Pyramid-Flow#205]
[
![Ekran görüntüsü 2024-12-01 212348](https://github.com/user-attachments/assets/86d20047-9476-4935-a146-bbba4d6cb2ec)
](url)

**Comment by nitinmukesh** [comment]
What is the error in command prompt?

**Comment by bihmet** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\pinokio\\api\\pyramidflow.git\\app\\Error during video generation: Torch not compiled with CUDA enabled'
[DEBUG] generate_text_to_video called.
[INFO] Starting text-to-video generation...
[ERROR] Error during text-to-video generation: Torch not compiled with CUDA enabled
[DEBUG] generate_text_to_video called.
[INFO] Starting text-to-video generation...
[ERROR] Error during text-to-video generation: Torch not compiled with CUDA enabled
