### ISSUE TITLE
2. Inference Code 太慢了

### ISSUE THREAD

**Issue by henbucuoshanghai** [jy0205/Pyramid-Flow#206]
使用最新readme里面的Inference Code和flux模型。A800显卡需要1h出结果，怎么回事，很慢。原始模型在哪呢。感谢

**Comment by zhichengsun** [comment]
There shouldn't be speed difference in miniflux and sd3 based versions. Could you please check if the (sequential) cpu_offloading modes are disabled?

**Comment by feifeiobama** [comment]
There shouldn't be any speed difference between miniflux and sd3 based versions. Could you please check if (sequential) CPU offloading is disabled?

**Comment by henbucuoshanghai** [comment]
(sequential) CPU offloading is disabled，then others to cuda,it about 1 mins for a video?
