### ISSUE TITLE
Suggestion about citing f-DM in the paper

### ISSUE THREAD

**Issue by SingleZombie** [jy0205/Pyramid-Flow#212]
I think paper f-DM: A Multi-stage Diffusion Model via Progressive Signal Transformation shares some similar ideas to this work: dividing the diffusion process into multiple scales, interpolating the denoising target within each scale, and preserving the variance in each jump point. The key difference is that f-DM builds on DDPM, while the work builds on Flow Matching. Considering the similarity of f-DM and this work, I suggest the authors mention f-DM in the final version of the paper to help readers learn more related works.

**Comment by feifeiobama** [comment]
Thank you for bring our attention to this paper, we will update the draft to provide a more comprehensive background.

(We have updated both arxiv and openreview versions, including the citation of f-DM)
