### ISSUE TITLE
PyramidFlow creates public link, weak security

### ISSUE THREAD

**Issue by ETCore7** [jy0205/Pyramid-Flow#217]
I should have posted the security issue here. PyramidFlow opens a public tunnel by invoking FRP for no reason. It should be disabled.
Link: [https://github.com/jy0205/Pyramid-Flow/discussions/215](https://github.com/jy0205/Pyramid-Flow/discussions/215)

**Comment by feifeiobama** [comment]
Thanks for your suggestion, we have enabled this as our cluster does not allow access with ssh port forwarding. Feel free to open a pull request and we will merge it as soon as possible.

**Comment by feifeiobama** [comment]
Fixed by https://github.com/jy0205/Pyramid-Flow/pull/225

**Comment by ETCore7** [comment]
Thank you.
