### ISSUE TITLE
Could use exact versions of packages used

### ISSUE THREAD

**Issue by vvuk** [jy0205/Pyramid-Flow#22]
It would be useful to have the exact versions of packages in use by the authors -- even just the output of `pip3 list` and `conda list` (if in use). I'm ending up with just black frames and would be nice to have a fully identical env to start from.

**Comment by feifeiobama** [comment]
For the black frame issue, are you using fp16 instead of bf16? We just saw a similar issue on https://github.com/jy0205/Pyramid-Flow/issues/25 and will fix it as soon as possible.

**Comment by vvuk** [comment]
That's fair. I was working with the repo here that only had the requirements.txt, though I sorted things out!

**Comment by jpgallegoar** [comment]
I got it working with this setup:

Windows11, Cuda 12.4, miniconda

(pyra) PS C:\Users\thega> python --version
Python 3.10.15
(pyra) PS C:\Users\thega> pip list
Package Version

accelerate 0.30.0
altair 5.4.1
annotated-types 0.7.0
asttokens 2.4.1
attrs 24.2.0
autocommand 2.2.2
backports.tarfile 1.2.0
blinker 1.8.2
blis 0.7.11
cachetools 5.5.0
catalogue 2.0.10
certifi 2024.8.30
cfgv 3.4.0
charset-normalizer 3.4.0
click 8.1.7
cloudpathlib 0.19.0
colorama 0.4.6
confection 0.1.5
contexttimer 0.3.3
contourpy 1.3.0
cycler 0.12.1
cymem 2.0.8
decorator 5.1.1
decord 0.6.0
diffusers 0.30.3
distlib 0.3.9
einops 0.8.0
exceptiongroup 1.2.2
executing 2.1.0
filelock 3.16.1
flash_attn 2.6.3
fonttools 4.54.1
fsspec 2024.9.0
ftfy 6.2.3
gitdb 4.0.11
GitPython 3.1.43
huggingface-hub 0.25.2
identify 2.6.1
idna 3.10
imageio 2.33.1
imageio-ffmpeg 0.5.1
importlib_metadata 8.5.0
importlib_resources 6.4.0
inflect 7.3.1
ipython 8.28.0
jaraco.collections 5.1.0
jaraco.context 5.3.0
jaraco.functools 4.0.1
jaraco.text 3.12.1
jedi 0.19.1
Jinja2 3.1.4
jsonlines 4.0.0
jsonschema 4.23.0
jsonschema-specifications 2024.10.1
kiwisolver 1.4.7
langcodes 3.4.1
language_data 1.2.0
lazy_loader 0.4
lightning-utilities 0.11.7
marisa-trie 1.2.0
markdown-it-py 3.0.0
MarkupSafe 3.0.1
matplotlib 3.9.2
matplotlib-inline 0.1.7
mdurl 0.1.2
more-itertools 10.3.0
mpmath 1.3.0
murmurhash 1.0.10
narwhals 1.9.2
networkx 3.3
nodeenv 1.9.1
numpy 1.26.4
opencv-python-headless 4.10.0.84
packaging 24.1
pandas 2.2.3
parso 0.8.4
pillow 10.4.0
pip 24.2
platformdirs 4.3.6
plotly 5.24.1
pre_commit 4.0.1
preshed 3.0.9
pretty-errors 1.2.25
prompt_toolkit 3.0.48
protobuf 5.28.2
psutil 6.0.0
pure_eval 0.2.3
pyarrow 17.0.0
pycocoevalcap 1.2
pycocotools 2.0.8
pydantic 2.9.2
pydantic_core 2.23.4
pydeck 0.9.1
Pygments 2.18.0
pyparsing 3.1.4
python-dateutil 2.9.0.post0
python-magic 0.4.27
pytz 2024.2
PyYAML 6.0.2
referencing 0.35.1
regex 2024.9.11
requests 2.32.3
rich 13.9.2
rpds-py 0.20.0
safetensors 0.4.5
scikit-image 0.24.0
scipy 1.14.1
sentencepiece 0.2.0
setuptools 75.1.0
shellingham 1.5.4
six 1.16.0
smart-open 7.0.5
smmap 5.0.1
spacy 3.7.5
spacy-legacy 3.0.12
spacy-loggers 1.0.5
srsly 2.4.8
stack-data 0.6.3
streamlit 1.39.0
sympy 1.13.3
tenacity 9.0.0
tensorboardX 2.6.2
thinc 8.2.5
tifffile 2024.9.20
tiktoken 0.8.0
timm 0.6.12
tokenizers 0.15.2
toml 0.10.2
tomli 2.0.1
torch 2.4.0+cu124
torchaudio 2.4.0+cu124
torchmetrics 1.4.2
torchvision 0.19.0+cu124
tornado 6.4.1
tqdm 4.66.5
traitlets 5.14.3
transformers 4.39.3
typeguard 4.3.0
typer 0.12.5
typing_extensions 4.12.2
tzdata 2024.2
urllib3 2.2.3
virtualenv 20.26.6
wasabi 1.1.3
watchdog 5.0.3
wcwidth 0.2.13
weasel 0.4.1
wheel 0.44.0
wrapt 1.16.0
zipp 3.20.2
