### ISSUE TITLE
different between paper and code

### ISSUE THREAD

**Issue by charlesliangcai** [jy0205/Pyramid-Flow#220]
Hi:
i have a question about code and paper
![image](https://github.com/user-attachments/assets/5a9fc274-86d9-44ea-a503-28284d2090b9)
![image](https://github.com/user-attachments/assets/73fa3b65-373d-445d-b047-26878d5c9d42)
"1 - start_sigma" in code  =  "start_sigma" in paper ?

**Comment by feifeiobama** [comment]
Nice observation! sigma usually indicates the coefficient of noise, and the weight on data in paper is 1-sigma.
