### ISSUE TITLE
Enviroment building error

### ISSUE THREAD

**Issue by WeizhenEricFang** [jy0205/Pyramid-Flow#29]
Hi, I kept getting error when I installed the given requirement.txt in the git repo by using the python 3.8.10. Is there any other env instruciton?

```
Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      Looking in indexes: https://mirrors.aliyun.com/pypi/simple
      Ignoring numpy: markers 'python_version >= "3.9"' don't match your environment
      Collecting setuptools
        Downloading https://mirrors.aliyun.com/pypi/packages/ff/ae/f19306b5a221f6a436d8f2238d5b80925004093fa3edea59835b514d9057/setuptools-75.1.0-py3-none-any.whl (1.2 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 14.9 MB/s eta 0:00:00
      Collecting cython<3.0,>=0.25
        Downloading https://mirrors.aliyun.com/pypi/packages/10/46/9a1b428442d09a6496d56e913ff4c3f4a1db119adc45d45ad2655bcb2a68/Cython-0.29.37-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 5.0 MB/s eta 0:00:00
      Collecting cymem<2.1.0,>=2.0.2
        Downloading https://mirrors.aliyun.com/pypi/packages/5f/70/b9945a7918d467c6c7112f6e20176d4f41b89d7ba0b590015b4cb62fb23d/cymem-2.0.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (46 kB)
      Collecting preshed<3.1.0,>=3.0.2
        Downloading https://mirrors.aliyun.com/pypi/packages/aa/7c/f36a498cb114765d0ecec946e6be46d2aadaea19317a1a1828e4aa2383d8/preshed-3.0.9-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (154 kB)
      Collecting murmurhash<1.1.0,>=0.28.0
        Downloading https://mirrors.aliyun.com/pypi/packages/f9/63/49e1eda3c610f49e5d3062e44ed27751f33ca8c4087b100b78b141201a6a/murmurhash-1.0.10-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29 kB)
      Collecting thinc<8.4.0,>=8.3.0
        Downloading https://mirrors.aliyun.com/pypi/packages/8a/9f/b2193b69dd112a46800182e897cda2fc9c497dfdd9352a0c5ba9252cf5f0/thinc-8.3.2.tar.gz (193 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error
      
        × pip subprocess to install build dependencies did not run successfully.
        │ exit code: 1
        ╰─> [44 lines of output]
            Looking in indexes: https://mirrors.aliyun.com/pypi/simple
            Ignoring numpy: markers 'python_version >= "3.9"' don't match your environment
            Collecting setuptools
              Downloading https://mirrors.aliyun.com/pypi/packages/ff/ae/f19306b5a221f6a436d8f2238d5b80925004093fa3edea59835b514d9057/setuptools-75.1.0-py3-none-any.whl (1.2 MB)
                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 6.0 MB/s eta 0:00:00
            Collecting cython<3.0,>=0.25
              Downloading https://mirrors.aliyun.com/pypi/packages/10/46/9a1b428442d09a6496d56e913ff4c3f4a1db119adc45d45ad2655bcb2a68/Cython-0.29.37-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 17.8 MB/s eta 0:00:00
            Collecting murmurhash<1.1.0,>=1.0.2
              Downloading https://mirrors.aliyun.com/pypi/packages/f9/63/49e1eda3c610f49e5d3062e44ed27751f33ca8c4087b100b78b141201a6a/murmurhash-1.0.10-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29 kB)
            Collecting cymem<2.1.0,>=2.0.2
              Downloading https://mirrors.aliyun.com/pypi/packages/5f/70/b9945a7918d467c6c7112f6e20176d4f41b89d7ba0b590015b4cb62fb23d/cymem-2.0.8-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (46 kB)
            Collecting preshed<3.1.0,>=3.0.2
              Downloading https://mirrors.aliyun.com/pypi/packages/aa/7c/f36a498cb114765d0ecec946e6be46d2aadaea19317a1a1828e4aa2383d8/preshed-3.0.9-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (154 kB)
            Collecting blis<1.1.0,>=1.0.0
              Downloading https://mirrors.aliyun.com/pypi/packages/bd/e4/741f20c9b767330e2605d4c71a775303cb6a9c72764b8802232fe6c7afad/blis-1.0.1.tar.gz (3.6 MB)
                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 13.4 MB/s eta 0:00:00
              Installing build dependencies: started
              Installing build dependencies: finished with status 'error'
              error: subprocess-exited-with-error
      
              × pip subprocess to install build dependencies did not run successfully.
              │ exit code: 1
              ╰─> [10 lines of output]
                  Looking in indexes: https://mirrors.aliyun.com/pypi/simple
                  Collecting setuptools
                    Downloading https://mirrors.aliyun.com/pypi/packages/ff/ae/f19306b5a221f6a436d8f2238d5b80925004093fa3edea59835b514d9057/setuptools-75.1.0-py3-none-any.whl (1.2 MB)
                       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.9 MB/s eta 0:00:00
                  Collecting cython>=0.25
                    Downloading https://mirrors.aliyun.com/pypi/packages/b2/52/eda119f98071ccde04a9a1c9c9a18fd6def025651c9d0cd01ad51d0dba36/Cython-3.0.11-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
                       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 12.5 MB/s eta 0:00:00
                  ERROR: Ignored the following versions that require a different python version: 1.25.0 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9; 1.26.2 Requires-Python >=3.9; 1.26.3 Requires-Python >=3.9; 1.26.4 Requires-Python >=3.9; 2.0.0 Requires-Python >=3.9; 2.0.1 Requires-Python >=3.9; 2.0.2 Requires-Python >=3.9; 2.1.0 Requires-Python >=3.10; 2.1.0rc1 Requires-Python >=3.10; 2.1.1 Requires-Python >=3.10; 2.1.2 Requires-Python >=3.10
                  ERROR: Could not find a version that satisfies the requirement numpy<3.0.0,>=2.0.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.
```

**Comment by JeremcyLU** [comment]
python 3.9.0 works for me,and you can follow the instructions by https://github.com/jy0205/Pyramid-Flow/issues/22#issuecomment-2406422182 which works for me too.The requirements.txt on the github leads to multiple versions of matlibplot which seems endless when installing by pip

**Comment by WeizhenEricFang** [comment]
> python 3.9.0 works for me,and you can follow the instructions by [#22 (comment)](https://github.com/jy0205/Pyramid-Flow/issues/22#issuecomment-2406422182) which works for me too.The requirements.txt on the github leads to multiple versions of matlibplot which seems endless when installing by pip

Thanks! But I tried python 3.9.0 and got an error as well. I am gonna try this #22

**Comment by jpgallegoar** [comment]
I got it working with this setup:

(pyra) PS C:\Users\thega> python --version
Python 3.10.15
(pyra) PS C:\Users\thega> pip list
Package                   Version
------------------------- ------------
accelerate                0.30.0
altair                    5.4.1
annotated-types           0.7.0
asttokens                 2.4.1
attrs                     24.2.0
autocommand               2.2.2
backports.tarfile         1.2.0
blinker                   1.8.2
blis                      0.7.11
cachetools                5.5.0
catalogue                 2.0.10
certifi                   2024.8.30
cfgv                      3.4.0
charset-normalizer        3.4.0
click                     8.1.7
cloudpathlib              0.19.0
colorama                  0.4.6
confection                0.1.5
contexttimer              0.3.3
contourpy                 1.3.0
cycler                    0.12.1
cymem                     2.0.8
decorator                 5.1.1
decord                    0.6.0
diffusers                 0.30.3
distlib                   0.3.9
einops                    0.8.0
exceptiongroup            1.2.2
executing                 2.1.0
filelock                  3.16.1
flash_attn                2.6.3
fonttools                 4.54.1
fsspec                    2024.9.0
ftfy                      6.2.3
gitdb                     4.0.11
GitPython                 3.1.43
huggingface-hub           0.25.2
identify                  2.6.1
idna                      3.10
imageio                   2.33.1
imageio-ffmpeg            0.5.1
importlib_metadata        8.5.0
importlib_resources       6.4.0
inflect                   7.3.1
ipython                   8.28.0
jaraco.collections        5.1.0
jaraco.context            5.3.0
jaraco.functools          4.0.1
jaraco.text               3.12.1
jedi                      0.19.1
Jinja2                    3.1.4
jsonlines                 4.0.0
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
kiwisolver                1.4.7
langcodes                 3.4.1
language_data             1.2.0
lazy_loader               0.4
lightning-utilities       0.11.7
marisa-trie               1.2.0
markdown-it-py            3.0.0
MarkupSafe                3.0.1
matplotlib                3.9.2
matplotlib-inline         0.1.7
mdurl                     0.1.2
more-itertools            10.3.0
mpmath                    1.3.0
murmurhash                1.0.10
narwhals                  1.9.2
networkx                  3.3
nodeenv                   1.9.1
numpy                     1.26.4
opencv-python-headless    4.10.0.84
packaging                 24.1
pandas                    2.2.3
parso                     0.8.4
pillow                    10.4.0
pip                       24.2
platformdirs              4.3.6
plotly                    5.24.1
pre_commit                4.0.1
preshed                   3.0.9
pretty-errors             1.2.25
prompt_toolkit            3.0.48
protobuf                  5.28.2
psutil                    6.0.0
pure_eval                 0.2.3
pyarrow                   17.0.0
pycocoevalcap             1.2
pycocotools               2.0.8
pydantic                  2.9.2
pydantic_core             2.23.4
pydeck                    0.9.1
Pygments                  2.18.0
pyparsing                 3.1.4
python-dateutil           2.9.0.post0
python-magic              0.4.27
pytz                      2024.2
PyYAML                    6.0.2
referencing               0.35.1
regex                     2024.9.11
requests                  2.32.3
rich                      13.9.2
rpds-py                   0.20.0
safetensors               0.4.5
scikit-image              0.24.0
scipy                     1.14.1
sentencepiece             0.2.0
setuptools                75.1.0
shellingham               1.5.4
six                       1.16.0
smart-open                7.0.5
smmap                     5.0.1
spacy                     3.7.5
spacy-legacy              3.0.12
spacy-loggers             1.0.5
srsly                     2.4.8
stack-data                0.6.3
streamlit                 1.39.0
sympy                     1.13.3
tenacity                  9.0.0
tensorboardX              2.6.2
thinc                     8.2.5
tifffile                  2024.9.20
tiktoken                  0.8.0
timm                      0.6.12
tokenizers                0.15.2
toml                      0.10.2
tomli                     2.0.1
torch                     2.4.0+cu124
torchaudio                2.4.0+cu124
torchmetrics              1.4.2
torchvision               0.19.0+cu124
tornado                   6.4.1
tqdm                      4.66.5
traitlets                 5.14.3
transformers              4.39.3
typeguard                 4.3.0
typer                     0.12.5
typing_extensions         4.12.2
tzdata                    2024.2
urllib3                   2.2.3
virtualenv                20.26.6
wasabi                    1.1.3
watchdog                  5.0.3
wcwidth                   0.2.13
weasel                    0.4.1
wheel                     0.44.0
wrapt                     1.16.0
zipp                      3.20.2

**Comment by WeizhenEricFang** [comment]
I have solved this with python 3.8.10 by following the https://github.com/user-attachments/files/17336831/env.txt

```
wheel==0.40.0
torch==2.1.2
contexttimer==0.3.3
decord==0.6.0
diffusers==0.30.3
accelerate==0.30.0
torchvision==0.16.2
numpy==1.24.4
einops==0.6.1
ftfy==6.2.3
ipython==8.12.3
opencv-python-headless==4.10.0.84
imageio==2.33.1
imageio-ffmpeg==0.5.1
packaging==23.1
pandas==2.0.3
plotly==5.18.0
pre-commit==3.3.3
python-magic==0.4.27
scikit-image==0.21.0
sentencepiece==0.1.99
spacy==3.7.2
streamlit== 1.29.0
timm==0.6.12
tqdm==4.64.1
transformers==4.39.3
torchmetrics==1.2.1
tiktoken==0.4.0
jsonlines==4.0.0
tensorboardX==2.6.2.2
async-timeout==4.0.2
multidict==6.0.4
jupyter_server==2.12.1
```

**Comment by titlestad** [comment]
# A fixed version, paste the content into myrequirements.txt and do
# pip install -r myrequirements.txt
accelerate==0.30.0
altair==5.4.1
annotated-types==0.7.0
asttokens==2.4.1
attrs==24.2.0
autocommand==2.2.2
backports.tarfile==1.2.0
blinker==1.8.2
blis==0.7.11
cachetools==5.5.0
catalogue==2.0.10
certifi==2024.8.30
cfgv==3.4.0
charset-normalizer==3.4.0
click==8.1.7
cloudpathlib==0.19.0
colorama==0.4.6
confection==0.1.5
contexttimer==0.3.3
contourpy==1.3.0
cycler==0.12.1
cymem==2.0.8
decorator==5.1.1
decord==0.6.0
diffusers==0.30.3
distlib==0.3.9
einops==0.8.0
exceptiongroup==1.2.2
executing==2.1.0
filelock==3.16.1
flash_attn==2.6.3
fonttools==4.54.1
fsspec==2024.9.0
ftfy==6.2.3
gitdb==4.0.11
GitPython==3.1.43
huggingface-hub==0.25.2
identify==2.6.1
idna==3.10
imageio==2.33.1
imageio-ffmpeg==0.5.1
importlib_metadata==8.5.0
importlib_resources==6.4.0
inflect==7.3.1
ipython==8.28.0
jaraco.collections==5.1.0
jaraco.context==5.3.0
jaraco.functools==4.0.1
jaraco.text==3.12.1
jedi==0.19.1
Jinja2==3.1.4
jsonlines==4.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
kiwisolver==1.4.7
langcodes==3.4.1
language_data==1.2.0
lazy_loader==0.4
lightning-utilities==0.11.7
marisa-trie==1.2.0
markdown-it-py==3.0.0
MarkupSafe==3.0.1
matplotlib==3.9.2
matplotlib-inline==0.1.7
mdurl==0.1.2
more-itertools==10.3.0
mpmath==1.3.0
murmurhash==1.0.10
narwhals==1.9.2
networkx==3.3
nodeenv==1.9.1
numpy==1.26.4
opencv-python-headless==4.10.0.84
packaging==24.1
pandas==2.2.3
parso==0.8.4
pillow==10.4.0
pip==24.2
platformdirs==4.3.6
plotly==5.24.1
pre_commit==4.0.1
preshed==3.0.9
pretty-errors==1.2.25
prompt_toolkit==3.0.48
protobuf==5.28.2
psutil==6.0.0
pure_eval==0.2.3
pyarrow==17.0.0
pycocoevalcap==1.2
pycocotools==2.0.8
pydantic==2.9.2
pydantic_core==2.23.4
pydeck==0.9.1
Pygments==2.18.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
python-magic==0.4.27
pytz==2024.2
PyYAML==6.0.2
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
rich==13.9.2
rpds-py==0.20.0
safetensors==0.4.5
scikit-image==0.24.0
scipy==1.14.1
sentencepiece==0.2.0
setuptools==75.1.0
shellingham==1.5.4
six==1.16.0
smart-open==7.0.5
smmap==5.0.1
spacy==3.7.5
spacy-legacy==3.0.12
spacy-loggers==1.0.5
srsly==2.4.8
stack-data==0.6.3
streamlit==1.39.0
sympy==1.13.3
tenacity==9.0.0
tensorboardX==2.6.2
thinc==8.2.5
tifffile==2024.9.20
tiktoken==0.8.0
timm==0.6.12
tokenizers==0.15.2
toml==0.10.2
tomli==2.0.1
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchmetrics==1.4.2
torchvision==0.19.0+cu124
tornado==6.4.1
tqdm==4.66.5
traitlets==5.14.3
transformers==4.39.3
typeguard==4.3.0
typer==0.12.5
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
virtualenv==20.26.6
wasabi==1.1.3
watchdog==5.0.3
wcwidth==0.2.13
weasel==0.4.1
wheel==0.44.0
wrapt==1.16.0
zipp==3.20.2

**Comment by WeizhenEricFang** [comment]
> # A fixed version, paste the content into myrequirements.txt and do
> # pip install -r myrequirements.txt
> accelerate==0.30.0 altair==5.4.1 annotated-types==0.7.0 asttokens==2.4.1 attrs==24.2.0 autocommand==2.2.2 backports.tarfile==1.2.0 blinker==1.8.2 blis==0.7.11 cachetools==5.5.0 catalogue==2.0.10 certifi==2024.8.30 cfgv==3.4.0 charset-normalizer==3.4.0 click==8.1.7 cloudpathlib==0.19.0 colorama==0.4.6 confection==0.1.5 contexttimer==0.3.3 contourpy==1.3.0 cycler==0.12.1 cymem==2.0.8 decorator==5.1.1 decord==0.6.0 diffusers==0.30.3 distlib==0.3.9 einops==0.8.0 exceptiongroup==1.2.2 executing==2.1.0 filelock==3.16.1 flash_attn==2.6.3 fonttools==4.54.1 fsspec==2024.9.0 ftfy==6.2.3 gitdb==4.0.11 GitPython==3.1.43 huggingface-hub==0.25.2 identify==2.6.1 idna==3.10 imageio==2.33.1 imageio-ffmpeg==0.5.1 importlib_metadata==8.5.0 importlib_resources==6.4.0 inflect==7.3.1 ipython==8.28.0 jaraco.collections==5.1.0 jaraco.context==5.3.0 jaraco.functools==4.0.1 jaraco.text==3.12.1 jedi==0.19.1 Jinja2==3.1.4 jsonlines==4.0.0 jsonschema==4.23.0 jsonschema-specifications==2024.10.1 kiwisolver==1.4.7 langcodes==3.4.1 language_data==1.2.0 lazy_loader==0.4 lightning-utilities==0.11.7 marisa-trie==1.2.0 markdown-it-py==3.0.0 MarkupSafe==3.0.1 matplotlib==3.9.2 matplotlib-inline==0.1.7 mdurl==0.1.2 more-itertools==10.3.0 mpmath==1.3.0 murmurhash==1.0.10 narwhals==1.9.2 networkx==3.3 nodeenv==1.9.1 numpy==1.26.4 opencv-python-headless==4.10.0.84 packaging==24.1 pandas==2.2.3 parso==0.8.4 pillow==10.4.0 pip==24.2 platformdirs==4.3.6 plotly==5.24.1 pre_commit==4.0.1 preshed==3.0.9 pretty-errors==1.2.25 prompt_toolkit==3.0.48 protobuf==5.28.2 psutil==6.0.0 pure_eval==0.2.3 pyarrow==17.0.0 pycocoevalcap==1.2 pycocotools==2.0.8 pydantic==2.9.2 pydantic_core==2.23.4 pydeck==0.9.1 Pygments==2.18.0 pyparsing==3.1.4 python-dateutil==2.9.0.post0 python-magic==0.4.27 pytz==2024.2 PyYAML==6.0.2 referencing==0.35.1 regex==2024.9.11 requests==2.32.3 rich==13.9.2 rpds-py==0.20.0 safetensors==0.4.5 scikit-image==0.24.0 scipy==1.14.1 sentencepiece==0.2.0 setuptools==75.1.0 shellingham==1.5.4 six==1.16.0 smart-open==7.0.5 smmap==5.0.1 spacy==3.7.5 spacy-legacy==3.0.12 spacy-loggers==1.0.5 srsly==2.4.8 stack-data==0.6.3 streamlit==1.39.0 sympy==1.13.3 tenacity==9.0.0 tensorboardX==2.6.2 thinc==8.2.5 tifffile==2024.9.20 tiktoken==0.8.0 timm==0.6.12 tokenizers==0.15.2 toml==0.10.2 tomli==2.0.1 torch==2.4.0+cu124 torchaudio==2.4.0+cu124 torchmetrics==1.4.2 torchvision==0.19.0+cu124 tornado==6.4.1 tqdm==4.66.5 traitlets==5.14.3 transformers==4.39.3 typeguard==4.3.0 typer==0.12.5 typing_extensions==4.12.2 tzdata==2024.2 urllib3==2.2.3 virtualenv==20.26.6 wasabi==1.1.3 watchdog==5.0.3 wcwidth==0.2.13 weasel==0.4.1 wheel==0.44.0 wrapt==1.16.0 zipp==3.20.2

Thanks!
