### ISSUE TITLE
I have 12 GB of VRAM, yet I'm still experiencing an out-of-memory (OOM) issue. Can someone specify how much RAM I need for it?

### ISSUE THREAD

**Issue by SAT431** [jy0205/Pyramid-Flow#32]

**Comment by Hussain-X** [comment]
Are you using cpu_offloading=True parameter?
As mentioned below:
https://github.com/jy0205/Pyramid-Flow/pull/23

**Comment by SAT431** [comment]
> Are you using cpu_offloading=True parameter? As mentioned below: #23

yes i used cpu_offloading=True and i have 24gb of ram and 12gb of vram. when it is trying to load models i getting like this:  (myenv) sathvik@sathvik:/mnt/c/Users/pasun/Music/Pyramid-Flow$ python app.py
Model directory '/mnt/c/Users/pasun/Music/Pyramid-Flow/pyramid_flow_model' already exists. Skipping download.
using half precision
Using temporal causal attention
We interp the position embedding of condition latents
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards:  50%|█████████████████████████████                             | 1/2 [00:45<00:45, 45.82s/it]Killed

**Comment by FurkanGozukara** [comment]
@SAT431 killed is out of ram error

You nerd buy more ram

**Comment by SAT431** [comment]
> FurkanGozukara

thank you
