### ISSUE TITLE
Where do I put the downloaded model?

### ISSUE THREAD

**Issue by eizoxx** [jy0205/Pyramid-Flow#34]
Those two inputs won't work on my device:

from huggingface_hub import snapshot_download

snapshot_download("rain1011/pyramid-flow-sd3", local_dir=model_path, local_dir_use_symlinks=False, repo_type='model')

![image](https://github.com/user-attachments/assets/c86c980c-e71d-48d1-9670-32c5c67e65ae)

What folder do I need to create, to put my model into?

**Comment by feifeiobama** [comment]
Create a folder called `pyramid_flow_model/` and download model checkpoints into it. The file structure should look like this:
```
pyramid_dit/
app.py
......
pyramid_flow_model/
    causal_video_vae/
    diffusion_transformer_384p/
    .......
```
Then, you can directly run `app.py` to launch a gradio demo:
https://github.com/jy0205/Pyramid-Flow/blob/5d85625f16d8807502ceac654e9f5f34460c47c6/app.py#L24-L25
This may be the easiest way. Alternatively, you need to modify the code to specify which folder the model checkpoint is downloaded to.

**Comment by eizoxx** [comment]
model_path = E:\AI\Pyramid-Flow\model # Directory to store the model

Like this?

**Comment by eizoxx** [comment]
> Yes, but I think you need to add quotation marks and use double backslashes:
> 
> ```python
> model_path = 'E:\\AI\\Pyramid-Flow\\model'  # Directory to store the model
> ```
> 
> Or use raw string literals:
> 
> ```python
> model_path = r'E:\AI\Pyramid-Flow\model'  # Directory to store the model
> ```

Thanks, that helped, but somehow my render time is 1.5 hours and my gpu is running at max performance which is 47.3 GB / 47,5 GB

`Model directory 'G:\Privat\AI\Pyramid-Flow\Pyramid_flow_model' already exists. Skipping download.
using half precision
Using temporal causal attention
We interp the position embedding of condition latents
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.69s/it]
The latent dimmension channes is 16
The start sigmas and end sigmas of each stage is Start: {0: 1.0, 1: 0.8002399489209289, 2: 0.5007496155411024}, End: {0: 0.6669999957084656, 1: 0.33399999141693115, 2: 0.0}, Ori_start: {0: 1.0, 1: 0.6669999957084656, 2: 0.33399999141693115}
Will cache examples in 'G:\Privat\AI\Pyramid-Flow\gradio_cached_examples\13' directory at first use.

C:\Users\user\.conda\envs\pyramid_new_2\lib\site-packages\gradio\analytics.py:106: UserWarning: IMPORTANT: You are using gradio version 4.44.1, however version 5.0.1 is available, please upgrade.
--------
  warnings.warn(

Will cache examples in 'G:\Privat\AI\Pyramid-Flow\gradio_cached_examples\25' directory at first use.


Running on local URL:  http://127.0.0.1:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.`

**Comment by feifeiobama** [comment]
Just a quick check: did you enable the `cpu_offloading` option, and have you looked at the RAM usage (in addition to VRAM)?

**Comment by eizoxx** [comment]
I set it to false now. And yeah, my ram was also going up, while running this thing. I'm currently running it an it is at 38% in 5 Minutes. vram is running at it's maximum... But it seems to be stuck again.
But just wondering, what is this?
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers

**Comment by feifeiobama** [comment]
> I set it to false now. And yeah, my ram was also going up, while running this thing. I'm currently running it and it is at 50% in 10 Minutes. vram is running at it's maximum... But it seems to be stuck again. RAM is also going up slowly again. Yesterday it was running at the half of it's performance... But just wondering, what is this? You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers

`add_prefix_space` is a default option in T5 tokenizer, see their comment for details:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/tokenization_t5.py#L115-L117

**Comment by eizoxx** [comment]
Here is how I installed pyramid-flow on my pc:

conda create -n pyramid python=3.8.10 (can I also install 3.9?)
conda activate pyramid

next, I got this error, when I tried to install the requirements.txt
_ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\pyramid_flow_env\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\user\.conda\envs\pyramid_flow_env\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\user\.conda\envs\pyramid_flow_env\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\user\.conda\envs\pyramid_flow_env\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\Users\user\.conda\envs\pyramid_flow_env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\user\.conda\envs\pyramid_flow_env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\user\.conda\envs\pyramid_flow_env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000_

This is why, I installed this instead:
pip install -r requirements.txt --use-deprecated=legacy-resolver

Also had to install this, as I got weird cuda errors:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

pip install gradio
pip show gradio

python app.py

**Comment by eizoxx** [comment]
If I use this command: conda remove --name <env_name> --all
Does this remove all the requirement.txt files from my system?

I deleted all conda pyramid environments I had and deleted all Pyramid Folders, I used with the gitclone command.
Can I now start normal with git clone ...?

**Comment by eizoxx** [comment]
What do I need to do to start over?

**Comment by eizoxx** [comment]
> > What do I need to do to start over?
> 
> Sorry for the late reply, please use `conda remove -n pyramid --all` to start over. The remaining issues seem to be two parts: 1) a pip dependency resolver error that may not be very important, 2) choosing a proper PyTorch 2.1.2 install command according to [this link](https://pytorch.org/get-started/previous-versions/) in accordance with your local CUDA version.

But what is he or she doing different, to get one minute for a video?
https://github.com/jy0205/Pyramid-Flow/issues/5#issuecomment-2406656030

**Comment by feifeiobama** [comment]
To get one minute for a video, switch to the 384p checkpoint. This required changing code in `app.py` in the old codebase, but has recently been integrated into the UI. Please use `git pull` or manually download the latest codebase to use this feature.
