### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [jy0205/Pyramid-Flow#4]
Hi,
Thanks for releasing Pyramid Flow! I noticed the HF repo was marked as MIT, would it be possible to add a license to the GitHub repo as well?
Thanks!

**Comment by feifeiobama** [comment]
Following your suggestion, we add the MIT License in commit https://github.com/jy0205/Pyramid-Flow/commit/e3389908eb34f08253f5f1e2c72f383ec052629d.
