### ISSUE TITLE
There is a big gap between the actual test results and the paper

### ISSUE THREAD

**Issue by xuzukang** [jy0205/Pyramid-Flow#47]
https://github.com/user-attachments/assets/d85c65b6-68e1-479b-9c96-161f944abbd2

This is the resolution 640x384, prompt: A side profile shot of a woman with fireworks exploding in the distance beyond her.

**Comment by feifeiobama** [comment]
Could you check if you used the right checkpoint (384p checkpoint for 384p generation)? We did not use a multi-resolution training strategy like CogVideoX, so our provided 768p checkpoint does not support 384p video generation.

**Comment by xuzukang** [comment]
Thank you for your answer. I did use the wrong model. 
I fixed this problem and found that my effect is already very good, but it is still a little different from the effect you published in https://pyramid-flow.github.io/ , especially the effect of the lady's side face in the video under lighting.
my result 
https://github.com/user-attachments/assets/bbd04576-6540-4a2d-83af-cc301ce40960

How can I get the same effect as you?
I tried the performance of the 768p model. My promt is: a cat is walking on the table. But the video obtained is very strange. Which parameters can be adjusted and optimized?

https://github.com/user-attachments/assets/5009bea2-4d5c-46f2-b1ca-ccf2971834cd

**Comment by feifeiobama** [comment]
Good to see you have solved the initial problem. We also find that there are sometimes live subject deformation and quality degradation issues in the current model checkpoint. These can be temporarily mitigated to some extent by tweaking the `video_guidance_scale` parameter, as smaller guidance can result in less motion and more stable video. We are also working on a new model checkpoint that seems to largely resolve the degradation issue when generating 384p video. We hope to share the progress soon.

**Comment by feifeiobama** [comment]
Good to see you have solved the initial problem. We also find that there are sometimes live subject deformation and quality degradation issues in the current model checkpoint. These can be temporarily mitigated to some extent by tweaking the `video_guidance_scale` parameter, as smaller guidance can result in less motion and more stable video. We are also working on a new model checkpoint that seems to largely resolve the degradation issue when generating 384p video. We hope to share the progress soon.
