### ISSUE TITLE
num_inference_steps and video_num_inference_steps values

### ISSUE THREAD

**Issue by ptits** [jy0205/Pyramid-Flow#49]
What are best values for 
           num_inference_steps=[steps, steps, steps],
            video_num_inference_steps=[video_steps,  video_steps,  video_steps],
 ?

I tried higher values like num_inference_steps=20 and  video_num_inference_steps=50 in results were worse then defaults (28)

Which are optimal?

Can you make some explanations for both?

**Comment by ptits** [comment]
https://github.com/user-attachments/assets/56bbbdd4-1af8-4598-8f99-5ff281e6cc28


https://github.com/user-attachments/assets/edb38f29-975d-42d3-9b56-af9f11fc1e19

**Comment by feifeiobama** [comment]
Thanks for the interesting observation. I recall that SD3 behaves similarly in that increasing the number of inference steps does not significantly improve performance. This is probably a limitation of ODE-based samplers, see [Restart Sampler](https://arxiv.org/abs/2306.14878) for more details.

**Comment by ptits** [comment]
Thanks!
What is difference between steps and video_steps

**Comment by jy0205** [comment]
The steps are used for generating the first frame, while video_steps are for video latent generation.

**Comment by ptits** [comment]
Thanks for ultra quick replies

In this case, why image2video uses
num_inference_steps only, not video-steps?

**Comment by jy0205** [comment]
Because the image-to-video does not need to regenerate the first frame. It directly uses the input image

**Comment by ptits** [comment]
Sorry for dumb questions:

"image-to-video does not need to regenerate the first frame." - so it should use video_steps, not steps.

Or I miss something, or naming convention is not obvious.

**Comment by feifeiobama** [comment]
The main concern has been addressed. We may improve the naming convention in future code refactorings.
