### ISSUE TITLE
Use sequential model offload at least on the text encoder.

### ISSUE THREAD

**Issue by rodjjo** [jy0205/Pyramid-Flow#51]
## What

If you use cpu_offload from accelerate  [example here](https://github.com/rodjjo/editorium/blob/7fcb0fa2c565c9dbf6c997fe6010aa9d7b390cab/editorium/app/server/pipelines/pyramid_flow/managed_model.py#L96)
you can use less memory when using the text encoder. 

## Why
To use even less VRAM.

# Note
Tried to do sequential offload on the DIT (not worked), however at least on the text_encoder it does.

@jy0205

**Comment by feifeiobama** [comment]
Thank you for contributing a memory saving plan. Feel free to make a pull request and we will integrate it into our pipeline.

**Comment by rodjjo** [comment]
@feifeiobama ~I'll do~ I did :D
https://github.com/jy0205/Pyramid-Flow/pull/75

**Comment by feifeiobama** [comment]
The pull request has been merged into the main branch :D
