### ISSUE TITLE
cpu_offloading=False

### ISSUE THREAD

**Issue by ptits** [jy0205/Pyramid-Flow#52]
If I set cpu_offloading=False generation does not start

model loaded ok

Starting text-to-video generation...
then freeze

Update: if I add three lines of code:
        model.vae.to("cuda")
        model.dit.to("cuda")
        model.text_encoder.to("cuda")
it starts working

**Comment by feifeiobama** [comment]
Could you detail which inference code you are using? I find that these three lines are already included in the `README.md` and the demo Jupyter notebook. We will fix it if they are missing from the original code.

**Comment by ptits** [comment]
these three lines are excluded from new version app.py

they were in old version

**Comment by feifeiobama** [comment]
Thank you for pointing this out. We will fix it as soon as possible.

**Comment by ptits** [comment]
Also in new app.py 
bf16 is frozen as default:

    model_dtype = "bf16"
    torch_dtype_selected = torch.bfloat16

old version had variable for that to try fp32 also

**Comment by feifeiobama** [comment]
The `app.py` has been updated in https://github.com/jy0205/Pyramid-Flow/commit/c78388a0afa9abffd79d68967f8f08391f7ec99c, please test it and see if it works. Feel free to submit a pull request if necessary.
