### ISSUE TITLE
Errors on Inference: Expected parameter covariance_matrix 

### ISSUE THREAD

**Issue by gjnave** [jy0205/Pyramid-Flow#53]
(Tensor of shape (4, 4)) of distribution MultivariateNormal(loc: torch.Size([4]), covariance_matrix: torch.Size([4, 4])) to satisfy the constraint PositiveDefinite(), but found invalid values:\ntensor([[ 1.0000, -0.3333, -0.3333, -0.3333],\n        [-0.3333,  1.0000, -0.3333, -0.3333],\n        [-0.3333, -0.3333,  1.0000, -0.3333],\n        [-0.3333, -0.3333, -0.3333,  1.0000]])'

**Comment by feifeiobama** [comment]
The covariance matrix is indeed **not** positive definite, but it seems to have worked well in our experiments. Could you describe your PyTorch version?

**Comment by gjnave** [comment]
> The covariance matrix is indeed **not** positive definite, but it seems to have worked well in our experiments. Could you describe your Python and PyTorch version?

torch                     2.4.1+cu118
torchmetrics              1.4.3
torchvision               0.19.1+cu118

**Comment by feifeiobama** [comment]
> > The covariance matrix is indeed **not** positive definite, but it seems to have worked well in our experiments. Could you describe your Python and PyTorch version?
> 
> torch 2.4.1+cu118 torchmetrics 1.4.3 torchvision 0.19.1+cu118

Thanks for the reply, could you try installing torch 2.1.2? It should also support CUDA 11.8 according to [this link](https://pytorch.org/get-started/previous-versions/#v212).

**Comment by gjnave** [comment]
> > > The covariance matrix is indeed **not** positive definite, but it seems to have worked well in our experiments. Could you describe your Python and PyTorch version?
> > 
> > 
> > torch 2.4.1+cu118 torchmetrics 1.4.3 torchvision 0.19.1+cu118
> 
> Thanks for the reply, I think this may be due to the torch version difference. Could you try installing torch 2.1.2? It should also support CUDA 11.8 according to [this link](https://pytorch.org/get-started/previous-versions/#v212).

thank you! that fixed it.
Could you briefly explain to me 1) how you figured out that was the problem and 2) how it resolved the problem?

thank you

**Comment by feifeiobama** [comment]
Sure. 1) When we derived the method and set the hyparameter $\gamma=-1/3$, we were afraid it might cause this error. It is actually a bit surprising to learn that the formulation works well with the cluster environment. So this may be a PyTorch version-specific lucky thing. 2) By using the exact PyTorch version we trained the model with, this error can be avoided.
