### ISSUE TITLE
How much ram is it needed? I have 24gb ram and when using cpu_offloading getting oom

### ISSUE THREAD

**Issue by SAT431** [jy0205/Pyramid-Flow#58]

**Comment by feifeiobama** [comment]
According to https://github.com/jy0205/Pyramid-Flow/pull/23#issuecomment-2406223821, it should take less than 12GB.

**Comment by SAT431** [comment]
i have 12gb vram but can you conform that how much ram it needed to load the model

**Comment by feifeiobama** [comment]
Sorry, I do not have an accurate stat about the RAM it needs. Please check our latest codebase which has optimized several issues with CPU offloading. Hope it works this time.

**Comment by Ednaordinary** [comment]
Here's a graph of ram usage over time. Around 20GB is required, preferably more as the system will take some
![image](https://github.com/user-attachments/assets/a1ad4302-f4e6-4182-9956-03c608a0a0ea)
