### ISSUE TITLE
ModuleNotFoundError: No module named 'pyramid_dit'

### ISSUE THREAD

**Issue by SiddiqueFarhan** [jy0205/Pyramid-Flow#6]
Getting the following error when using the code

Code:
import torch
from PIL import Image
from pyramid_dit import PyramidDiTForVideoGeneration
from diffusers.utils import load_image, export_to_video

torch.cuda.set_device(0)
model_dtype, torch_dtype = 'bf16', torch.bfloat16   # Use bf16, fp16 or fp32	

model = PyramidDiTForVideoGeneration(
    'PATH',                                         # The downloaded checkpoint dir
    model_dtype,
    model_variant='diffusion_transformer_768p',     # 'diffusion_transformer_384p'
)

model.vae.to("cuda")
model.dit.to("cuda")
model.text_encoder.to("cuda")
model.vae.enable_tiling()

Error:
ModuleNotFoundError: No module named 'pyramid_dit'

Environment Details:
I am using the code on Google Colab with TPU attached.

Looking forward. Thanks for attention.

Best regards,
Farhan

**Comment by jpgallegoar** [comment]
pyramid_dit is a folder inside this repository

**Comment by SiddiqueFarhan** [comment]
Thank you for the information. Just checked it. Can you please let me know how can I install this repo using pip?

**Comment by jpgallegoar** [comment]
You must do " git clone https://github.com/jy0205/Pyramid-Flow/ " wherever you want this repository to be (any folder). So you must have git installed if that doesn't work. Perhaps you could wait a few days until a more beginner friendly version comes out (it most definitely will), such as a ComfyUi node.

**Comment by kexul** [comment]
> Thank you for the information. Just checked it. Can you please let me know how can I install this repo using pip?

Actually you dont need to install it. just clone the repo and then add 
```python 
import sys
sys.path.append('Pyramid-Flow')
``` 
before your inference script.

**Comment by SiddiqueFarhan** [comment]
Thanks @kexul  and @jpgallegoar. This worked well. Closing the issue.

**Comment by SiddiqueFarhan** [comment]
use the following command to clone the repo:
!git clone https://github.com/jy0205/Pyramid-Flow/

and then change the current working directory by:
import os
os.chdir('/content/Pyramid-Flow')
