### ISSUE TITLE
((LIVE@STREAMS)) 2024 Mr. OlYmPiA LiVe 𝐒​𝐭​𝐫​𝐞​𝐚​𝐦​𝐬 FrEe BrOaDcAsT oN tV cHaNnEl 13 October 2024

### ISSUE THREAD

**Issue by arifcartaba** [jy0205/Pyramid-Flow#68]
The best in bodybuilding has taken to Las Vegas this week for Joe Weider's Olympia Fitness and Performance Weekend, home to the prestigious Mr. Olympia event.

Saturday, the history books will add a new winner, with several former winners looking to secure their second title.

One such competitor is 2023 winner Derek Lunsford, who outperformed the rest of the field en route to his first Mr. Olympia title, and will have a chance to become the first repeat champion since Mamdouh Elssbiay in 2020 and '21.

Saturday Events

Mr. Olympia

Men's Physique Olympia

Bikini Olympia

Classic Physique Olympia

All events are scheduled for 7:00 p.m.

Past Winners

Joining Lunsford as previous champions competing in this year's competition are 2022 winner Hadi Choopan and 2019 victor Brandon Curry. They will look to become multi-time titleholders, joining the sport's most decorated stars.

Multi-time champions have been common since the inaugural days of the event.

Larry Scott kicked things off, winning the first and second events. Sergio Oliva picked up where he left off, winning the next three. While those two athletes would lay the groundwork for the industry, introducing the Terminator himself sparked interest in the sport and help catapult it to new heights.

Arnold Schwarzenegger, the most recognizable face in the industry's long history, won six consecutive Mr. Olympia events from 1970 through 1975 before Hollywood came calling.

Arnold Schwarzenegger competing at Mr. Olympia in 1975. <a href="https://t.co/y9dw5klekI">pic.twitter.com/y9dw5klekI</a>

He returned to the industry in 1980 and proved he still had it, winning a seventh title.

Frank Zane and Dorian Yates would go on to leave their lasting legacies as repeated victors who dominated the sport for extended periods before Jay Cutler and Phil Heath all defined eras in bodybuilding with their long strings of dominance.

Phil Haney and Ronnie Coleman are the most prolific winners, tied for eight Mr. Olympia victories, making them the most decorated to compete in the event.

Mr. Olympia LLC
@MrOlympiaLLC
Ronnie Coleman <br>8x Mr.Olympia 🏆🏆🏆🏆🏆🏆🏆🏆<br>Full Time Bodybuilder &amp; Full Time Police Officer<a href="https://twitter.com/MrOlympiaLLC?ref_src=twsrc%5Etfw">@mrolympiallc</a> <a href="https://twitter.com/hashtag/mrolympia?src=hash&amp;ref_src=twsrc%5Etfw">#mrolympia</a> <a href="https://t.co/ntdAWYOwm3">pic.twitter.com/ntdAWYOwm3</a>

It remains to be seen if Lunsford or Choopan can add a second title to their resumes. They have tough competition in the form of Samson Douda, a bodybuilder whose physique is rivaled by few and could easily be deemed the best in the show on Saturday night in Las Vegas.

The quality of talent in the sport right now, too, could make it difficult for one competitor to go on the type of run that Schwarzenegger, Coleman, Haney, and the others have experienced. The deeper the talent pool, the less likelihood that a given performer can fend off his opposition for any extended period of time.

Still, there is an opportunity for history to be made Saturday with a Lunsford or Choopan victory.

And an entirely different kind of history should Douda, the most obvious threat to either man, earn the nod from the judges.

**Comment by feifeiobama** [comment]
Closed due to irrelevant content.
