### ISSUE TITLE
Very good work, when Training code release?

### ISSUE THREAD

**Issue by huangjch526** [jy0205/Pyramid-Flow#8]

**Comment by Delong-liu-bupt** [comment]
+1

**Comment by feifeiobama** [comment]
We are currently working on two priorities: a Huggingface demo, and a new model checkpoint trained from scratch (we have almost finished its 384p video training). We plan to start cleaning up the training code after these two issues and will release it as soon as possible.

**Comment by jquintanilla4** [comment]
Great work. Looking forward to learning more about the training.

**Comment by runzeer** [comment]
@feifeiobama Could you release the 384p video training version in advance? Really looking forward to the details of the training.

**Comment by feifeiobama** [comment]
We have open-sourced the training code :D
