### ISSUE TITLE
DO I NEED CUDA?! What about solely GPU processing?

### ISSUE THREAD

**Issue by Loganius-II** [jy0205/Pyramid-Flow#83]
soo this is my output:
[DEBUG] generate_text_to_video called.
[INFO] Initializing model with variant='768p', using bf16 precision...
[DEBUG] Model base path: C:\Users\user\OneDrive\Desktop\coding\Python\Pyramid-Flow\PATH
using half precision
Using temporal causal attention
We interp the position embedding of condition latents
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.41s/it]
The latent dimmension channes is 16
The start sigmas and end sigmas of each stage is Start: {0: 1.0, 1: 0.8002399489209289, 2: 0.5007496155411024}, End: {0: 0.6669999957084656, 1: 0.33399999141693115, 2: 0.0}, Ori_start: {0: 1.0, 1: 0.6669999957084656, 2: 0.33399999141693115}
[WARNING] CUDA is not available. Proceeding without GPU.
[INFO] Model initialized successfully.
[INFO] Starting text-to-video generation...
C:\Python312\Lib\site-packages\torch\amp\autocast_mode.py:265: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
[ERROR] Error during text-to-video generation: Torch not compiled with CUDA enabled

I dont want to use cuda like brooo

**Comment by feifeiobama** [comment]
Our codebase only supports PyTorch with CUDA enabled, since it is more friendly for training and inference. Feel free to share your thoughts :)
