### ISSUE TITLE
Do you have interest in adding RIFE support (it would double the frame rate) ?

### ISSUE THREAD

**Issue by rodjjo** [jy0205/Pyramid-Flow#85]
## What

[Rife](https://github.com/hzwer/ECCV2022-RIFE) is a tool that does a frame interpolation (create frames between two frames) to increase the frame rate.

By adding that It would convert the 24fps to 48fps or so.

I'm asking here because 24fps seems to be enough, if not, we could just add RIFE as an example about how to increase the FPS even more.

## Why

To double the frame rate.

[reference](https://github.com/rodjjo/editorium/blob/a7fab602ee4b9973b5a5a896a690df7831aa5d8f/editorium/app/server/pipelines/common/save_video.py#L48)

**Comment by feifeiobama** [comment]
I think the bottleneck of the current model is not frame rate, but rather stability. We hope to first address that and then look at these enhancements.

Anyway, thank you for the thoughtful suggestion.
