### ISSUE TITLE
Negative prompt

### ISSUE THREAD

**Issue by ptits** [jy0205/Pyramid-Flow#88]
Will it work? I see it is presented as an argument for model input and defaulted to:
"cartoon style, worst quality, low quality, blurry, absolute black, absolute white, low res, extra limbs, extra digits, misplaced objects, mutated anatomy, monochrome, horror"

I did not test it - just need to ask, does it make sense to play with it? Will it influence generation?

**Comment by feifeiobama** [comment]
Yes, we find that the negative prompt is very helpful for both visual quality and temporal stability. We do not yet know the mechanism, as the captions we used did not include these prompts. We will investigate this in the new model training process.
