### ISSUE TITLE
Face distortion

### ISSUE THREAD

**Issue by kexul** [jy0205/Pyramid-Flow#9]
Experiencing severe face distortion with image to video, here is an example:
![977](https://github.com/user-attachments/assets/991e0a16-9d77-4106-bc09-0989f3493a2f)

https://github.com/user-attachments/assets/6bf8cbb2-21aa-49fc-a58a-65aea56e212d

**Comment by kexul** [comment]
Prompt: "Man smiling".

**Comment by jy0205** [comment]
This may be due to image resizing, as current models only support resolutions of 640x384 or 1280x768. Therefore, the input image is resized to meet these requirements. However, direct resizing can result in distortion. Maybe you can try resizing by keeping the aspect ratio and then cropping?

**Comment by kexul** [comment]
> This may be due to image resizing, as current models only support resolutions of 640x384 or 1280x768. Therefore, the input image is resized to meet these requirements. However, direct resizing can result in distortion. Maybe you can try resizing by keeping the aspect ratio and then cropping?

Thanks, keep ration resize produce better result: 

https://github.com/user-attachments/assets/67dffa90-ad22-470f-883c-f9b7e616b140

**Comment by kexul** [comment]
Not really...

https://github.com/user-attachments/assets/6491f00e-61a1-4d91-a4b9-ca2311323e90

**Comment by feifeiobama** [comment]
Please try using a smaller `video_guidance_scale` which may produce smaller motion and more stable video.

Regarding the face/teeth/hand distortion, we have also noticed similar issues during early tests, and believe it is related to the SD3 weight initialization. We are therefore training a new model checkpoint from scratch and are currently finishing the 384p video training. We will test this case on our new model checkpoint, and will keep you updated.

**Comment by feifeiobama** [comment]
Closed as the miniFLUX checkpoint has been released.
