### ISSUE TITLE
image generation?

### ISSUE THREAD

**Issue by ptits** [jy0205/Pyramid-Flow#93]
if duration set to 1 - may be output PNG for testing t2v first frame?
just an idea
requiring  fixing seed of course

**Comment by dillfrescott** [comment]
I think you might be better off using flux if you want to do text to image as it can't do video but might yield higher results on single frames.

**Comment by feifeiobama** [comment]
The image generation capability of this model is from 100m+ images (and 10m video initial frames), with some knowledge inherited from SD3. We suggest using specialized image generation models instead.
