### ISSUE TITLE
生成的视频是黑屏

### ISSUE THREAD

**Issue by theoldsong** [jy0205/Pyramid-Flow#99]
非常棒的项目，感谢作者开源
RT，生成后，时长是对的，但是播放是黑屏，这是什么原因？

**Comment by sunflower110** [comment]
你是否使用的是fp16数据类型，我也遇到同样的问题

**Comment by feifeiobama** [comment]
Our model does not support FP16. Please use FP32 if your device does not support BF16. (1) Without (sequential) CPU offloading, this may be feasible, but will require more VRAM than our reported 8GB requirement. (2) It would help if you have multiple GPUs to use the multi-GPU inference feature.

**Comment by theoldsong** [comment]
> 你是否使用的是fp16数据类型，我也遇到同样的问题

是的
